### PR TITLE
A big part of translation of french

### PR DESCRIPTION
**Pull request by achul123**

### CODE REVIEW

**Comment by achul123** [comment]
I'll translate more when I can

**Review by NaysKutzu — COMMENTED** [review]
Till now, it looks cool, but I will look more into it when you are done, and then I will merge it to the develop branch, and it will be on the new update!

**Comment by achul123** [comment]
I'm going to finish now but it will take about 30min.

**Comment by achul123** [comment]
it just takes a long time x)

**Comment by achul123** [comment]
I didn't translate some sentences because they just didn't make sense in French.

**Comment by NaysKutzu** [comment]
> I didn't translate some sentences because they just didn't make sense in French.

What do you mean?

**Comment by NaysKutzu** [comment]
And it looks like your syntax is broken to :(

**Comment by achul123** [comment]
Ah

**Comment by achul123** [comment]
And now ?

**Comment by NaysKutzu** [comment]
Still no the placeholders look to be broken they have to be uppercase !

**Review by NaysKutzu — APPROVED** [review]
Looks good to me

**Pull request merged**
