### PR TITLE
Rename Meteor to Heliactyl 14

### PR DESCRIPTION
**Pull request by ethzr**
Meteor was renamed to Heliactyl 14 in December 2023, I also fixed the features of it

### CODE REVIEW

**Review by NaysKutzu — CHANGES_REQUESTED** [review]
You have to prove that those changes actually exists and work!

**Comment by ethzr** [comment]
- No version of Heliactyl (even back to v5) is vulnerable to XSS
- Custom CSS and other features have been here since v12 (and have been expanded with v14)
- A coin leaderboard has existed in Heliactyl since the versions in between v12 and v14, can confirm this by seeing any images of my older dashboards such as Flux or Pulsar
- "advanced encryption" doesn't mean much but Heliactyl has always been one of the most secure dashboards
- Activity logs was merged with Heliactyl when we began bringing features from Palladium and Skyport over
- Search was added in v14 release 22620 in January 2024, it is available on Polaris if you'd like to see it working

**Review by NaysKutzu — APPROVED** [review]
Looks good with those changes tbh!

**Comment by ethzr** [comment]
add a tick for web logs and CLI
- live web & access logs are available via lightning in admin -> system -> lightning
- CLI was added back in December when we began transitioning some products and services to go instead of js

**Pull request merged**
